development:
  sessions:
    default:
      database: learning
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      hosts:
        - flame.mongohq.com:27046
      database: app5628866
      another:
        uri: <%= ENV['MONGOHQ_URL'] %>