development:
  sessions:
    default:
      database: learning
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: app5628866
      another:
        uri: <%= ENV['MONGOHQ_URL'] %>