<%
/:\/\/(.+?):(.+?)@(.+?)\/(.+?)$/ =~ ENV['MONGOHQ_URL']
username = $1
password = $2
host = $3
database = $4
%>
development:
  clients:
    default:
      database: learning
      hosts:
        - localhost:27017
production:
  clients:
    default:
      database: <%= database %>
      hosts:
        - <%= host %>
      options:
        user: <%= username %>
        password: <%= password %>

