<%
/:\/\/(.+?):(.+?)@(.+?)\/(.+?)$/ =~ ENV['MONGOHQ_URL']
username = $1
password = $2
host = $3
database = $4
%>
development:
  sessions:
    default:
      database: learning
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: <%= database %>
      hosts:
        - <%= host %>
      username: <%= username %>
      password: <%= password %>
  options:
    skip_version_check: true
